name: Actions Workflow

on:
    - push

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Simple JS Action
              id: greet
              # instead of v1 you can also use a branch name or a commit id to reference a specific version of an action
              uses: actions/hello-world-javascript-action@v1
              with:
                  who-to-greet: Marco
            - name: Log greeting time
              run: echo "${{ steps.greet.outputs.time }}"
